[versions]
kotlin = "2.3.0"
ktor = "3.4.0"
logback = "1.5.21"
ksoup = "0.2.5"
graalvm = "0.11.3"

[libraries]
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
ksoup-kotlinxIo = { module = "com.fleeksoft.ksoup:ksoup-kotlinx", version.ref = "ksoup" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
graalvm = { id = "org.graalvm.buildtools.native", version.ref = "graalvm" }
